### ISSUE TITLE
ImportError: No module named sqlite

### ISSUE THREAD

**Issue by hannah98** [moul/docker-readthedocs#10]
I followed the instructions but when the docker-compose gets to the point of running this application, it fails with this trace:

```
+ /venv/bin/python manage.py syncdb --noinput
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
   File "/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/readthedocs/config.py", line 1, in <module>
    from readthedocs.settings.sqlite import *
ImportError: No module named sqlite
```

`

It looks like 5 days ago there was a commit on the [rtd repo](https://github.com/rtfd/readthedocs.org/commit/b749c5022fabfa68571117b42bebd74d20fcf126) to change the settings, specifically on [line 6 of the manage.py](https://github.com/rtfd/readthedocs.org/commit/b749c5022fabfa68571117b42bebd74d20fcf126#diff-632b651e5579af0e928ed63482e9bc77L6) file.

**Comment by moul** [comment]
Hi @hannah98, nice catch, I will update the script to reflect last changes in manage.py

**Comment by moul** [comment]
Hi, I just fixed the issue, can you try again ?

**Comment by hannah98** [comment]
Yes! That fixed it - thanks!

Sorry it took a while - I didn't get notifications that you had replied - I came back today and discovered you had already fixed it.
