### ISSUE TITLE
Import not working :: Redis Error

### ISSUE THREAD

**Issue by dklesev** [moul/docker-readthedocs#2]
After got it running I get this here when I want to import a repo:

```
[27/Feb/2014 03:29:15] ERROR [projects.tasks:679] (Build) [docker-readthedocs:latest] Failed to symlink cnames, Redis error. 
Traceback (most recent call last): 
File "readthedocs/projects/tasks.py", line 677, in symlink_cnames 
cnames = redis_conn.smembers('rtd_slug:v1:%s' % version.project.slug) 
File "/venv/local/lib/python2.7/site-packages/redis/client.py", line 974, in smembers 
return self.execute_command('SMEMBERS', name) 
File "/venv/local/lib/python2.7/site-packages/redis/client.py", line 363, in execute_command 
connection.send_command(*args) 
File "/venv/local/lib/python2.7/site-packages/redis/connection.py", line 299, in send_command 
self.send_packed_command(self.pack_command(*args)) 
File "/venv/local/lib/python2.7/site-packages/redis/connection.py", line 281, in send_packed_command 
self.connect() 
File "/venv/local/lib/python2.7/site-packages/redis/connection.py", line 229, in connect 
raise ConnectionError(self._error_message(e)) 
ConnectionError: Error 111 connecting localhost:6379. Connection refused. 
```

**Comment by kwisatz** [comment]
I don't think you can expect an answer from this project's author… after 10 months.

**Comment by moul** [comment]
I made some fixes which seems to works, can you try again ?

**Comment by kwisatz** [comment]
On 2014-12-04 14:54, Manfred Touron wrote:

> I made some fixes which seems to works, can you try again ?

OK, I was wrong ;) Thanks @moul

Do you happen to have any documentation on the use of redis (and 
elasticsearch) with ReadTheDocs? I can't find any documentation for that 
and I'd very much like to know what they're used for.
I mean, they don't seem to be necessary, because the builds work fine 
without them, but still.

**Comment by moul** [comment]
@kwisatz : No I don't, sorry, I mainly built this image because there were none at the moment and I wanted something autonomous and simple :)

In my case, I built small documentations and didn't notice any slowness
